### ISSUE TITLE
Accessors for Ast children?

### ISSUE THREAD

**Issue by jagill** [prove-rs/z3.rs#106]
We're trying to port a Python lib that uses the Python Z3 bindings to Rust.  One functionality gap we came across is the ability to traverse the Ast by accessing a node's children.  In python, there are [functions](https://github.com/Z3Prover/z3/blob/master/src/api/python/z3/z3.py#L1026) for `children`, `num_args`, and `arg`.  I'd be very interested in those in z3.rs!

I've opened an RFC PR #105.  Some reasons for caution:
1. I don't really understand the Z3 C API and the right memory model to make sure my `unsafe` blocks are actually safe.
2. I chose the more intuitive names of `num_children` and `nth_child` rather than `num_args` and `arg`, but maybe it's better to keep the APIs similar?
3. I've just done a few basic tests.  I'm happy to do more, if you think I'm going in the right direction.

And thanks for making this crate, btw!  It's very helpful to us.

**Comment by fitzgen** [comment]
Yeah, it makes sense to support this functionality. I'll leave details to pr #105.

> And thanks for making this crate, btw! It's very helpful to us.

Your welcome. It has had a few maintainers over the years--starting with Graydon, then Bruce, and now me--so I definitely can't claim 100% credit, but I'm sure they would appreciate the kind words as well.
