### ISSUE TITLE
Examining AST types (eg DeclKind)

### ISSUE THREAD

**Issue by jagill** [prove-rs/z3.rs#115]
My goal is to parse an AST, converting it to a representation used in another library.  For example, if the other representation is of the form:
```rust
enum Node {
  BoolLiteral(bool),
  BoolVar(String),
  And(Box<Node>, Box<Node>),
  Or(Box<Node>, Box<Node>),
}
```

I'd like a z3 AST `x and (y or true)` to be converted to (dropping boxes/etc)

```rust
And(BoolVar("x"), Or(BoolVar("y"), BoolLiteral(true)))
```

This requires being able to introspect the Ast types at the DeclKind granularity.  In the Python/C++ API, they have functions such as `Ast::kind() -> AstKind`, `Ast::func_decl() -> FuncDecl`, `FuncDecl::kind() -> DeclKind`, etc.  My initial attempts to mimic those APIs to do this have been partially successful, but ultimately cause errors.  The current issue is that my implementation `FuncDecl::kind() -> DeclKind` (pasted below) is returning an invalid DeclKind (value 0, while Z3_decl_kind starts at 256), but I suspect the larger issue is that I am bad at C and I am monkey coding.

I'd be very interested in having the path of methods that lead to getting `DeclKind`.  I'm happy to send out PRs that may or may not work, but it's also possible that you could do this in your sleep and I'd just get in the way :).

**Comment by fitzgen** [comment]
Care to make a draft PR so that I can take a look at the code and leave comments?

**Comment by jagill** [comment]
You got it: #116

**Comment by sameer** [comment]
> (pasted below) is returning an invalid DeclKind (value 0, while Z3_decl_kind starts at 256), but I suspect the larger issue is that I am bad at C and I am monkey coding.

@jagill could you share this code? I tried out the following:

```rust
#[test]
fn test_func_application() {
    let cfg = Config::default();
    let ctx = Context::new(&cfg);

    let unary_decl = FuncDecl::new(&ctx, "unary", &[&Sort::bool(&ctx)], &Sort::bool(&ctx));
    let x = Bool::from_bool(&ctx, false);
    let y = unary_decl.apply(&[&x.clone().into()]);
    assert_eq!(y.kind(), AstKind::App);
    assert_eq!(y.decl().kind(), DeclKind::UNINTERPRETED);
}

```

Which passes

**Comment by jagill** [comment]
@sameer Thanks for looking into this!  But I think I've worked through it -- there was a component of user error, compounded by incorrect debugging output in VS Code/LLDB.
