### ISSUE TITLE
Implement interface for Tactic and Goal

### ISSUE THREAD

**Issue by rlkelly** [prove-rs/z3.rs#124]
There is currently no abstraction on Tactic or Goal, which are useful for things like simplification.  I started working on implementing them, but wanted to check if there had been some work on this in the past or any blockers for adding them to the library.

**Comment by fitzgen** [comment]
> wanted to check if there had been some work on this in the past or any blockers for adding them to the library.

None that I'm aware of; go for it!

**Comment by rlkelly** [comment]
to follow up, I made a PR here: https://github.com/prove-rs/z3.rs/pull/125/
