### ISSUE TITLE
Holding a reference in `DatatypeAccessor::Sort` is awkward

### ISSUE THREAD

**Issue by Mcat12** [prove-rs/z3.rs#138]
(repeating some context from #137)

The issue with taking a reference to `Sort` is that a pattern like the following no longer works:
```rust
// Translating my own type system into Z3, specifically structs
let my_name: String = ...;
let my_fields: Vec<(String, IrType)> = ...;
let z3_types: HashMap<IrType, DatatypeSort> = ...;

let builder = DatatypeBuilder::new(context, "foo");
let variants = my_fields
    .iter()
    .map(|(name, field)| {
        let z3_ty = match field {
            IrType::Bool => DatatypeAccessor::Sort(Sort::bool(context)),
            // ... other simple types ...
            not_simple_type => {
                let z3_ty: &DatatypeSort = z3_types.get(not_simple_type).unwrap();
                DatatypeAccessor::Sort(z3_ty.sort.clone())
            }
        };
        (name.as_str(), z3_ty)
    })
    .collect();

let new_ty: DatatypeSort<'ctx> = builder.variant("foo_variant", variants).finish();
z3_types.insert(my_name, new_ty);
```

`z3_ty` sometimes refers to a sort that lives on the stack, so it can't be returned from the map function. The fix is to make a single sort value outside of the loop (even if the sort will not be used by the variant) so it can be referred to in `variants`, but can this be avoided? Switching back to the owned `Sort` value and adding a `Clone` impl would do this (clone impl was added in #137).

**Comment by sameer** [comment]
So in this example, are you returning z3_types later on? This is the test I'm working with to try and understand the issue:

```rust
#[test]
fn test_issue_138() {
    fn return_datatype<'ctx>(
        ctx: &'ctx Context,
        types: &[DatatypeSort<'ctx>],
    ) -> DatatypeSort<'ctx> {
        let accessors = types
            .iter()
            .map(|sort| ("foo_accessor", DatatypeAccessor::Sort(&sort.sort)))
            .collect::<Vec<_>>();
        DatatypeBuilder::new(ctx, "foo")
            .variant("bar", accessors)
            .finish()
    }
    let cfg = Config::new();
    let ctx = &Context::new(&cfg);
    let ty = return_datatype(ctx, vec![]);
}
```

It seems to work fine, is there something I'm missing here?

**Comment by Mcat12** [comment]
This is my actual code: https://github.com/Mcat12/static-bf4/blob/c9249721d0731b1b8f2642d9b48f2a84b37768d8/src/generate_z3_types.rs#L25

I'm converting from my internal `IrType` into Z3 types. I have a struct type which is where I utilize Z3's data types. Structs can be nested, so I'm traversing them in order of dependency and transforming them into Z3 data types. Each struct field needs to be transformed into `DatatypeAccessor`'s before the struct data type can be built, which is where the `map` is introduced. Let me know if that helps, and thanks for responding so quickly and nicely!

**Comment by sameer** [comment]
Interesting, I'll check it out first thing tomorrow. Thanks for sharing that reference

**Comment by sameer** [comment]
So the awkwardness here was originally not being able to clone the sorts. But now after #113 and #137, it's let bindings for sorts versus cloning, correct?

**Comment by Mcat12** [comment]
The awkwardness is having to create sorts outside of the `map` loop which I may never use. It's probably not that big of a deal now that it's references because they are `Copy`, but it's awkward to have to create each possible primitive sort upfront.

**Comment by Mcat12** [comment]
There is another case which makes this awkward. I have a type which is parameterized by an integer (`bit<N>`, a sequence of N bits). Since there can be many different versions of this type (`bit<1>`, `bit<8>`, etc), there could be any number of different sorts that need to be generated. It's quite awkward to generate these sorts up front and then reference them when making the data types. It would be much easier to make the sorts as needed and pass the owned `Sort` value to `DatatypeAccessor::Sort`.

**Comment by sameer** [comment]
I agree with you on this, cloning the sort seems to be the ideal solution. Would you be able to create a revert PR for #113 ?

**Comment by Mcat12** [comment]
Yes, I will make a PR to revert the change to sort references.
