### ISSUE TITLE
Can 0.11.0 be released recently?

### ISSUE THREAD

**Issue by LEAFERx** [prove-rs/z3.rs#150]
As title. I find it useful for function declaration with body and recursion. Thanks!

**Comment by sameer** [comment]
Hi Lawrence, it's been on my mind :slightly_smiling_face: 

I was hoping to close out discussion on #143 and merge that change, but in the interest of time I'll publish 0.11 now.

**Comment by sameer** [comment]
Closed by a2526c88629a2f38f1e78ea896546b8e739451b4
