### ISSUE TITLE
Rust newbie: fatal error at installation: 'z3.h' file not found

### ISSUE THREAD

**Issue by pcarbonn** [prove-rs/z3.rs#156]
After I've added a z3 dependency to Cargo.toml, `cargo run` attempts to install the z3 crate, but fails when buidling z3-sys, with the error above.  Obviously, it cannot locate the Z3 solver.

How can that be fixed ?  Am I supposed to have the Z3 solver's source code in my rust project repository, including z3.h ? Or add a link to a shared library ?

**Comment by pcarbonn** [comment]
Silly me.  The fix is to [build Z3](https://github.com/pcarbonn/z3#building-z3-using-make-and-gccclang) and install it using `sudo make install`.

I now get the error `'stddef.h' file not found`.  Not sure why.

**Comment by pcarbonn** [comment]
Now fixed.  I had to `sudo apt install clang-9` as suggested [here](https://github.com/include-what-you-use/include-what-you-use/issues/679#issuecomment-656882050), but for it to work, I had first to downgrade libc6-dev, as suggested [here](https://askubuntu.com/a/1338046) for Ubuntu 20.04 .  Pfew !

Feel free to update the docs or close this issue.

**Comment by sameer** [comment]
Hi pcarbonn,

z3-sys tries to find Z3 on your system and generate bindings for that. Unless I am mistaken,  this is common behavior for Rust *-sys projects using bindgen/cmake.

As called out in the [z3 installation instructions](https://github.com/prove-rs/z3.rs/tree/master/z3#installation), you can instead choose static linking to compile Z3 as a part of the build process.

I do see Z3 [available on Ubuntu 20.04](https://packages.ubuntu.com/focal/z3), but it is a bit outdated.

**Comment by pcarbonn** [comment]
Thanks.  I did try to install Z3 using apt, but it did not work for some reason.

The documentation is fine, so, I'll close the issue.

**Comment by sameer** [comment]
The issues with static linking should be resolved with v0.11.2 + sys v0.7.1. Hopefully that makes using Z3 in Rust a bit easier 🙂
