### ISSUE TITLE
Optimize gives wrong, unstable results

### ISSUE THREAD

**Issue by ancorehraq** [prove-rs/z3.rs#159]
I have an integer minimization problem that gives different results depending on the order in which assertions are added. If I feed the generated SMT 2.0 code to the standalone z3 executable, the result is always correct.

Repro code: https://github.com/ancorehraq/z3_repro1/blob/master/src/main.rs (sorry it's so big, I tried to minimize it as much as I could)

Output:
...
bad: true, answer: 84
...
bad: false, answer: 51

"z3 -model" with either variant produces:
...
  (define-fun used_ORE () Int
    51)
...

**Comment by ancorehraq** [comment]
Ah, I didn't realize z3.rs builds against system z3. I get the bad result with z3 4.8.7 (Ubuntu focal), but not 4.8.10 (Ubuntu hirsuite).

:shrug:

**Comment by sameer** [comment]
FWIW, you can statically link z3 for more consistent results with `static-link-z3`. We currently track z3 v4.8.12
