### ISSUE TITLE
How do I call `Z3_mk_tuple_sort`?

### ISSUE THREAD

**Issue by ahelwer** [prove-rs/z3.rs#167]
Here's the function signature:
```rust
pub unsafe extern "C" fn Z3_mk_tuple_sort(
    c: Z3_context, 
    mk_tuple_name: Z3_symbol, 
    num_fields: c_uint, 
    field_names: *const Z3_symbol, 
    field_sorts: *const Z3_sort, 
    mk_tuple_decl: *mut Z3_func_decl, 
    proj_decl: *mut Z3_func_decl
) -> Z3_sort
```
See docs [here](https://docs.rs/z3-sys/0.6.3/z3_sys/fn.Z3_mk_tuple_sort.html). I'm stuck on how I'm supposed to create the last two parameters. So for creating a key-value tuple sort with two strings, I have:
```rust
let str_sort = Z3_mk_string_sort(ctx);
let kv_tuple = to_z3_symbol(ctx, "key_value_tuple");
let key_field = to_z3_symbol(ctx, "key");
let value_field = to_z3_symbol(ctx, "value");
let field_names = [key_field, value_field];
let field_sorts = [str_sort, str_sort];
let tuple_sort =
  Z3_mk_tuple_sort(
    ctx,
    kv_tuple,
    2,
    field_names.as_ptr(),
    field_sorts.as_ptr(),
    ???,
    ???
  );
```
The documentation for the final two parameters reads:
>mk_tuple_decl: output parameter that will contain the constructor declaration.
proj_decl: output parameter that will contain the projection function declarations. This field must be a buffer of size num_fields allocated by the user.

However, that doesn't really make sense - if I pass in a pointer to some allocated memory for `proj_decl` using `std::alloc::alloc`:
```rust
let constructor_layout = Layout::new::<_Z3_func_decl>();
let mut constructor = alloc(constructor_layout) as Z3_func_decl;
let field_projectors_layout = Layout::new::<[_Z3_func_decl; 2]>();
let mut field_projectors = alloc(field_projectors_layout) as Z3_func_decl;
```
then the pointer itself is changed, as the parameter type implies. So it seems this call allocates memory for you?

**Comment by GreenBeard** [comment]
@ahelwer I think this isn't an issue with this library, and it seems like not the appropriate spot to post this in my opinion, but I was wondering if you were still having issues with this as I see that you received a reply on stackoverflow. If you resolved your issue then would you mind closing this issue? If not then maybe this will help https://stackoverflow.com/questions/16137005/set-membership-relation-in-z3. If you are still struggling I can try to help (by reading about this function as I'm not familiar with this specific z3 function), but I cannot promise that I will figure it out. :shrug:

**Comment by ahelwer** [comment]
@GreenBeard oh yeah I switched to the Python API for prototyping my project. I think it would be useful to keep this open so I can eventually integrate the logic into the higher level z3 package once I figure it out.
