### ISSUE TITLE
z3-sys cannot find z3.h

### ISSUE THREAD

**Issue by DavePearce** [prove-rs/z3.rs#172]
Hey,

So, following the docs it says to resolve this configure `Z3_SYS_Z3_HEADER` to the actual path.  But, that doesn't seem to be resolving the issue.  Here are my commands:

```
> setenv Z3_SYS_Z3_HEADER /home/.../include/z3.h
> echo $Z3_SYS_Z3_HEADER
 /home/.../include/z3.h
> cargo run
```

I tried doing `cargo clean` first, but not difference.  Did I miss something?

**Comment by DavePearce** [comment]
I should add that I'm actually linking against `z3` not `z3-sys`.

**Comment by jmc-figueira** [comment]
It seems to me that the issue is that the option to use that environment variable to specify the path explicitly was added after the latest published version of the library. Hence, you need to use the version from the latest git commit (`ef6ca05cac901795112444fd805f25b06a1d5526`) to be able to use that.

**Comment by dcsommer** [comment]
It would be great to enhance the path finding in general to not require users manually specify the path by environment variables. One place to start for inspiration could be this CMake script:

https://github.com/klee/klee/blob/master/cmake/modules/FindZ3.cmake

**Comment by Ablu** [comment]
Would something like https://github.com/rust-lang/rust-bindgen/issues/1247 maybe be a more flexible approach? That would also fix the auto-detection on Fedora (which has the header under `/usr/include/z3/z3.h`). @futile would a pkg-config based detection have worked in your situation? (mentioning since you opened the PR for the configurable header path)

**Comment by Ablu** [comment]
I digged around a bit. The OpenCV wrapper has something pretty sophisticated. I am not suggesting to copy it 1:1, but taking a peek there was certainly interesting: https://github.com/twistedfall/opencv-rust/blob/master/build/library.rs. They derive stuff from all kind of sources (environment variables, pkg_config, cmake, vcpkg). I think either cmake or pkg_config would be a great start and solve 90%+ of the problems?

**Comment by futile** [comment]
> @futile would a pkg-config based detection have worked in your situation? (mentioning since you opened the PR for the configurable header path)

Hey! :) I don't think a pkg-config based detection would have worked in my situation, as I built z3 from source as well (possibly in different configurations), and thus just wanted it to point at the correct file. So I think it would be nice to keep the environment override around in some form, but pkg-config and/or cmake detection capabilities don't sound like they would be mutually exclusive. Thanks for the ping, appreciate it! :)

**Comment by Ablu** [comment]
@futile ah ok. Does z3 do not install it's pkg-config to some path that would be settable via `PKG_CONFIG_PATH` when doing a local build?

Though, it looks like https://docs.rs/system-deps/latest/system_deps/#overriding-build-flags could be helpful. It can pull from both the pkg-config, but also from environment overrides. It seems to be used by a fair bit of other larger libs too (https://crates.io/crates/system-deps/reverse_dependencies). That might be the best of "all" the worlds maybe?

**Comment by futile** [comment]
Mhhm, to be honest I'm not really familiar with pkg-config, but if it provides a way to just say "use this directory/file" then I guess that would work just as well.
