### ISSUE TITLE
future-incompatibilities raised by z3-sys

### ISSUE THREAD

**Issue by Xuanwo** [prove-rs/z3.rs#237]
z3-sys 0.7.1 will lead to:

```shell
warning: the following packages contain code that will be rejected by a future version of Rust: nom v5.1.2
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 2`
```

This has been fixed in `main`, how about bumping a new version for z3-sys? Thanks.

**Comment by Xuanwo** [comment]
Hi @waywardmonkeys and @Pat-Lafon, could you please take a look? z3-sys has not been released for 2 years.

**Comment by Pat-Lafon** [comment]
I don't have any influence on this, it's up to @waywardmonkeys.

**Comment by waywardmonkeys** [comment]
I've done some merges and a couple of fixes. Is there anything else before I do a 0.8 release? Should I bump `z3` itself to 0.12 or just increment the patch version?

**Comment by Xuanwo** [comment]
> Should I bump `z3` itself to 0.12 or just increment the patch version?

Since z3-sys is being updated to v0.8, it would be advisable to also upgrade z3 to version 0.12.

**Comment by waywardmonkeys** [comment]
Done!
