### ISSUE TITLE
Question/discussion/suggestion: AST subtypes

### ISSUE THREAD

**Issue by cdisselkoen** [prove-rs/z3.rs#31]
Trying to combine `Ast`s of different `Sort`s often results in errors.  For instance, you can't `add` an integer and a bitvector, you can only `select` on an array, etc.  In fact, the `Ast` type appears to have a number of distinct groups of methods, only one of which applies to any given `Ast` (depending on its `Sort`): the first group (`add`, `sub`, etc) which apply to integers (and maybe reals? Not sure as I never use reals); the second group (`bv*`) which apply to bitvectors; `select` and `store` which apply to arrays; `set_*` which apply to sets; and `pb_*` (I'm not sure what these are either).

Since each of these groups of methods apply to different kinds of `Ast`s, and rarely can different kinds of `Ast`s be mixed without errors, I was wondering if any thought has been given to splitting `Ast` into a number of subtypes, perhaps `IntAst`, `BVAst`, `ArrayAst`, etc (obviously different names could be used).  This would not only clarify exactly which `Ast` operations apply to each type, it would also help prevent more errors statically at the Rust type level, thus making a safer set of high-level bindings.

I'm potentially willing to help implement this if it's desired and feasible, but I wanted to ask first if it's a reasonable suggestion, and get feedback from anyone with more experience with Z3 (and Rust) than me.  Is there a reason this is a bad idea?

**Comment by waywardmonkeys** [comment]
I want this as well.

**Comment by waywardmonkeys** [comment]
We could have a trait per operation (add, sub, etc) with input / output types like `std::ops` and then impl that for the various types and invoke the right underlying primitive (bvadd, etc).
