### ISSUE TITLE
Invalid CStr construction

### ISSUE THREAD

**Issue by Shadlock0133** [prove-rs/z3.rs#50]
In [sort](https://github.com/prove-rs/z3.rs/blob/6355bd326f737c47510475b95575198d8b86129b/z3/src/sort.rs#L126), [ast](https://github.com/prove-rs/z3.rs/blob/9cc8ce708422db8d8a662b3535da7b6b9eaa4d54/z3/src/ast.rs#L288), [solver](https://github.com/prove-rs/z3.rs/blob/3878e6211ef0552c051528035710300726de497b/z3/src/solver.rs#L226), [params](https://github.com/prove-rs/z3.rs/blob/3878e6211ef0552c051528035710300726de497b/z3/src/params.rs#L50), and [optimize](https://github.com/prove-rs/z3.rs/blob/6355bd326f737c47510475b95575198d8b86129b/z3/src/optimize.rs#L109); constructing CStr from null pointer [will cause a segfault](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=11eea66879dbed8bdefe30f80cb4c2cf) and is probably an UB. Checking if pointer is null should be moved before CStr construction.

**Comment by waywardmonkeys** [comment]
Thanks. This is fixed on `master` now in commit 1004e56.
