### ISSUE TITLE
New crates.io release

### ISSUE THREAD

**Issue by djrenren** [prove-rs/z3.rs#51]
Hi! seeing as the crate has undergone some sizable refactoring lately, would it be possible to release a new version on crates.io?

**Comment by waywardmonkeys** [comment]
I want to ... I've been talking with @cdisselkoen about one change that I'd like to see first ...

I have just returned home (temporarily perhaps) from a month of travel, so I'm working through a backlog of things now to get caught up.

**Comment by waywardmonkeys** [comment]
cc: @hengchu who has also asked about a new release.

**Comment by waywardmonkeys** [comment]
@cdisselkoen This is a sketch of the change to `Sort` that I was talking about before:

    https://github.com/prove-rs/z3.rs/commit/6f76b87ed65fa91ce4b1ef18e10e8296876ef8bf

I'm not totally sure about it. I think there's an advantage to moving to a trait rather than an enum. This would let us express some things more clearly with respect to types ... like that the sort of some values must be a FloatingPoint or what not.

Thoughts?

**Comment by cdisselkoen** [comment]
Hm interesting.  I have a few questions/comments.

1) I like how this makes the code look cleaner.  `Sort` no longer has lifetime parameters, and can now be constructed without passing in a Z3 context.  Hopefully this would be more convenient for crate users as well.
2) Is this proposal less efficient?  Essentially every Z3 call that requires a `Sort` parameter will now also involving constructing and destructing a Z3 sort object.  Previously Z3 sort objects could be reused across multiple calls.
3) Should we be concerned that all of the refcounting for the `Z3_sort` objects is gone?  I'm not too familiar with Z3's requirements for when things are refcounted or not.

Overall this proposal seems to me like a question of ergonomics vs. efficiency, unless I'm wrong about some of the points above.  I'm not sure exactly where I stand on it yet.  For me, it probably comes down to "how much ergonomics gain" vs. "how much efficiency loss" for real crate users.  Interested to hear your (or others') thoughts on this.

(Direct link to the commit: 6f76b87ed65fa91ce4b1ef18e10e8296876ef8bf)

**Comment by djrenren** [comment]
So I've actually been working on something similar to clean up the API, so here's my thoughts:

## Design Constraints
Z3 allows most sorts to be instantiated multiple times (including more exotic ones like finite domains), but disallows multiple instantiations of others (such as datatypes).

For this reason, we need a type that unifies these inert `SortDescriptions` and live `Sort`s that are known to Z3. 

## Approach

To me, a trait seems like a really good way to express this:

```rust
trait SortDescription {
     fn instantiate<'ctx>(&self, ctx: &'ctx Context) -> Sort<'ctx>;
}
```

For already instantiated sorts, this is a noop:

```rust
impl<'ctx> SortDescription for Sort<'ctx> {
     fn instantiate<'out_ctx: 'ctx>(self, &'out_ctx Context) -> Self {
          self
     }
}
```
(there's a few lifetimes to work out exactly, but I think it'll sort itself out during implementation)

and for the primitives we have:

```rust
impl SortDescription for Int {
          fn instantiate<'ctx>(&self, ctx: &'ctx Context) -> Sort<'ctx> {
                 Z3_mk_int_sort(ctx)
          }
}
```
and so on. I think these sort primitives should not be all members of the same enum.

We can use a `SortKind` enum as the return value for functions that inspect sorts.

Then our functions that, today, accept `Sort<'ctx>`, instead accept either `&dyn SortDescription`, `Box<dyn SortDescription>` or `impl SortDescription`.

This way, users can opt for the simpler approach of lifetime-less `SortDescription`'s in most cases, but in key scenarios like datatypes can manage things the old way.

Thoughts?

**Comment by djrenren** [comment]
Okay so, I've determined this is doable, but I'm not sure there's an elegant way to short-circuit the reference counting that comes from constructing full `Sort<'ctx>`'s.

The issue is that if we use a trait, rather than an enum, we have to expose all the methods on it, meaning we'd have to expose a method that returns raw `Z3_sort`s which is probably not ideal. 

The enum approach has its own problem, where one of the variants needs to be a `SortRef(Sort<'ctx>)` which would reintroduce the lifetime parameter we wanted to remove.

**Comment by waywardmonkeys** [comment]
I think I'm going to release a new version with the current state of `master` ... probably within the next 12 hours. And we can keep iterating for the next release. :)

**Comment by waywardmonkeys** [comment]
Sorry, I haven't been feeling great and got sidetracked. I will do this today for sure. Thanks for the reminder / ping!

**Comment by waywardmonkeys** [comment]
z3-sys 0.5.0 and z3 0.4.0 are released now!
