### ISSUE TITLE
Ast::substitute is unsafe

### ISSUE THREAD

**Issue by djrenren** [prove-rs/z3.rs#52]
The substitute method on AST allows arbitrary rewriting while retaining (now inaccurate) types.

```
<Int as Ast>::substitute<Int, Real>
```

could internally rewrite the Ast to be of type `Real`, but retain the rust type `Int`. 

for the function to be safe, we need the more restricted type:

```
substitute<T>(&self, substitutions: &[(&T, &T)]) -> Self
```

Or some extra machinery to handle the invalid or retyped ASTs that can be formed by arbitrary substitution.

**Comment by waywardmonkeys** [comment]
Oof. This is a great point. Cc'ing @hengchu who wrote that. Any chance that one of you would like to take this on?

**Comment by waywardmonkeys** [comment]
If someone wants a better fix, that's welcome, but for now, I did the simple fix as given by @djrenren above.

**Comment by hengchu** [comment]
Ah sorry about the remiss. This fix looks good to me! Thank you for catching that.
