### ISSUE TITLE
Segfault when compiling --release

### ISSUE THREAD

**Issue by DnMllr** [prove-rs/z3.rs#53]
Forgive me, I'm new to Z3. I was experimenting and I wanted to create a program that solves a sorted list of variables from 0 to 100. My code runs and finds the solution, albeit slowly, when compiled in development mode, but Segfaults when compiled in release mode. I figured I'd raise an issue.

Here's my code:

```rust
extern crate z3;

use z3::ast;
use z3::*;

fn main() {
    let cfg = Config::new();
    let ctx = Context::new(&cfg);
    let optimizer = Optimize::new(&ctx);

    let mut v = Vec::new();

    for i in 0..100 {
        let c = ast::Int::new_const(&ctx, format!("cell-{}", i));
        if i == 0 {
            optimizer.assert(&c.gt(&ast::Int::from_i64(&ctx, 0)))
        }
        optimizer.minimize(&c);
        v.push(c);
    }

    for (i, j) in v.iter().zip(v.iter().skip(1)) {
        optimizer.assert(&j.gt(i));
    }

    assert!(optimizer.check());

    let model = optimizer.get_model();

    for i in v.iter() {
        println!("{}: {}", i, model.eval(i).unwrap().as_i64().unwrap());
    }
}
```

**Comment by DnMllr** [comment]
My version of z3 is `Z3 version 4.8.5 - 64 bit` and my `cargo.toml` has `z3 = {git = "https://github.com/prove-rs/z3.rs"}`.

**Comment by jrakow** [comment]
Unfortunately, as far as I know, version 4.8 is not supported by the bindings.
Z3 introduced a few breaking changes from 4.7 to 4.8.

I tried porting the bindings a while ago and the semver example, which also used the optimizer, stopped working as well. Does the issue persist with 4.7?

**Comment by DnMllr** [comment]
It does work with 4.7. Thank you!

**Comment by waywardmonkeys** [comment]
This needs to get fixed. Most of us are using Z3 4.8 with the bindings, and in fact, when there's a new Z3 release, that'll be necessary for macOS so that we can improve the threading.

Let's keep this open to get this fixed. There's another issue about the semver example as well.

**Comment by waywardmonkeys** [comment]
This was an issue where the Z3 API had changed, but we hadn't updated yet.

I fixed that in fea326b56876b79448bf3d8b688a7d311fa8bd61.

Let me know if things are better now please.

**Comment by DnMllr** [comment]
It is fixed! Thank you.

**Comment by waywardmonkeys** [comment]
Great!
