### ISSUE TITLE
Distinguish "unknown" from "unsat"

### ISSUE THREAD

**Issue by fpoli** [prove-rs/z3.rs#55]
Currently, using the `Solver::check` method, there is no way to distinguish an "unknown" answer from an "unsat".

One (non backward compatible) solution would be to:
1. add a `LiftedBool` enum, with variants `True`, `False`, and `Undefined`
2. rename `Solver::check` to `Solver::is_sat`
3. add a `Solver::check` method that returns a `LiftedBool`

**Comment by waywardmonkeys** [comment]
Yes, adding a `LiftedBool` and then changing `Solver::check` and `Solver::check_assumptions` to return that instead of `bool` sounds like the correct thing to do.

If you'd like to do that and submit a PR, let me know. Otherwise, I'll get to it in about 15 hours.

**Comment by waywardmonkeys** [comment]
(and the doc comments will need updating as well.)

**Comment by waywardmonkeys** [comment]
Fixed in #56.
