### ISSUE TITLE
Can't choose a symbolic array index?

### ISSUE THREAD

**Issue by tnballo** [prove-rs/z3.rs#70]
I'm storing a fixed/known number of binary expressions in an array and solving for the index of an expression that evaluates to a specific result (i.e. pick the operator to "switch" on, given all expressions have the same operands). This works in Python, but I can't seem to translate it to the Rust bindings. Simplified example:

Below works fine in Python (package `z3-solver` version `4.8.7.0`), solving for `8 (operator) 3 = 24` I get `2`, the index of operator `*`, the correct result:

Python code:
```python
from z3 import *

s = Solver()

result = IntVal(24)
x = IntVal(8)
y = IntVal(3)

A = Array ('A', IntSort(), IntSort())
A = Store(A, 0, x - y)
A = Store(A, 1, x + y)
A = Store(A, 2, x * y)

j = Int('j')
s.add(j >= 0)
s.add(j <= 2)

goal = (Select(A, j) == result)
s.add(goal)
print("Goal: {}".format(goal))

if s.check() == sat:
  print("Model: {}".format(s.model()))
else:
  print("Not found!")
```
Python output:
```
Goal: 24 == Store(Store(Store(A, 0, 8 - 3), 1, 8 + 3), 2, 8*3)[j]
Model: [j = 2]
```

However, trying to write the equivalent in Rust (crate `z3` version `0.4`, Ubuntu `libz3-dev` version `4.4.1`), I get `0`, the index of the `-` operator, which is incorrect:

```rust
extern crate z3;
use z3::ast::Ast;

let config = z3::Config::new();
let ctx = z3::Context::new(&config);
let solver = z3::Solver::new(&ctx);

let result = z3::ast::Int::from_u64(&ctx, 24);
let x = z3::ast::Int::from_u64(&ctx, 8);
let y = z3::ast::Int::from_u64(&ctx, 3);

let A = z3::ast::Array::new_const(&ctx, "A", &z3::Sort::int(&ctx), &z3::Sort::int(&ctx));

A.store(
    &z3::ast::Dynamic::from_ast(&z3::ast::Int::from_u64(&ctx, 0)),
    &z3::ast::Dynamic::from_ast(&x.sub(&[&y])),
);

A.store(
    &z3::ast::Dynamic::from_ast(&z3::ast::Int::from_u64(&ctx, 1)),
    &z3::ast::Dynamic::from_ast(&x.add(&[&y])),
);

A.store(
    &z3::ast::Dynamic::from_ast(&z3::ast::Int::from_u64(&ctx, 2)),
    &z3::ast::Dynamic::from_ast(&x.mul(&[&y])),
);

let j = z3::ast::Int::new_const(&ctx, "j");
solver.assert(&j.ge(&z3::ast::Int::from_u64(&ctx, 0)));
solver.assert(&j.le(&z3::ast::Int::from_u64(&ctx, 2)));

let goal = A
    .select(&z3::ast::Dynamic::from_ast(&j))
    ._eq(&z3::ast::Dynamic::from_ast(&result));
solver.assert(&goal);
println!("Goal: {}", goal);

if solver.check() == z3::SatResult::Sat {
    println!("Model: {}", solver.get_model());
} else {
    println!("Not found!");
}
```
Rust output:
```
Goal: (= (select A j) 24)
Model: A -> (_ as-array k!0)
j -> 0
k!0 -> {
  0 -> 24
  else -> 24
}
```

Any idea what might be going wrong here?

Thanks in advance!

**Comment by tnballo** [comment]
Slightly different output for above code when using `libz3-dev` version `4.8.4` (latest available on Ubuntu 19.10), but problem persists!

```
Goal: (= (select A j) 24)
Model: A -> (lambda ((x!1 Int)) 24)
j -> 0
```

**Comment by sameer** [comment]
@tnballo `store`-ing does not mutate the array A, it creates a new array wrapping A. So you need to change things a bit:

```
let mut A = ...;
A = A.store(..);
```

like how you have it set up for Python

**Comment by tnballo** [comment]
@sameer Thank you, really appreciate it! Get below correct output for the Rust version with your suggested fix:
```
Goal: (= (select (store (store (store A 0 (- 8 3)) 1 (+ 8 3)) 2 (* 8 3)) j) 24)
Model: j -> 2
```

Closing issue since my problem is *solved* (couldn't resist).
