### ISSUE TITLE
Debugging?

### ISSUE THREAD

**Issue by ksqsf** [prove-rs/z3.rs#77]
Hi,

I'm generating some assertions, but z3 complains type errors. I wanted to print out the details of the context. For example, print the SMTLib2 format. But z3-rs seems to have no support for any kind of inspection? I'd like to know what to do in this case...

I'm not familiar with z3-rs or z3-c++, so please forgive me if I make any mistakes.

**Comment by fitzgen** [comment]
The debug formatters will print the smt lib2 representation of your queries:

```rust
let ctx = z3::Context::new();
let x = z3::ast::BV::from_u64(&ctx, 2, 32);
let y = z3::ast::BV::from_u64(&ctx, 3, 32);
let z = z3::ast::BV::from_u64(&ctx, 5, 32);
let my_query = x.bvadd(y)._eq(z);
println!("my query is: {:?}", my_query);
```

You can also set the `RUST_LOG` environment variable to `trace` and initialize a logger (e.g. [`env_logger`](https://crates.io/crates/env_logger)) to get a bunch of extra diagnostic messages.

**Comment by ksqsf** [comment]
Hi. Thanks for your pointer. I have found the bug in my code. However, it's still very annoying to add `dbg!`s everywhere and then remove them.

Is there a simple way to print out all consts and assertions in a context?

PS: I tried `RUST_LOG=trace` but the output is not very helpful from the perspective of a library user.

```
[2020-05-19T04:53:28Z DEBUG z3::config] new config 0x7fd663408688
[2020-05-19T04:53:28Z DEBUG z3::context] new context 0x7fd663811008
[2020-05-19T04:53:28Z DEBUG z3::ast] new ast: id = 5, pointer = 0x7fd66381b1f8
[2020-05-19T04:53:28Z DEBUG z3::ast] new ast: id = 6, pointer = 0x7fd66381b218
[2020-05-19T04:53:28Z DEBUG z3::ast] new ast: id = 7, pointer = 0x7fd66381b238
[2020-05-19T04:53:28Z DEBUG z3::ast] drop ast: id = 6, pointer = 0x7fd66381b218
```

**Comment by fitzgen** [comment]
I would be happy to merge a PR that added `debug`-level logging of assertions given to a context in the `z3::Solver::assert` and `z3::Solver::assert_and_track` methods, if you would like to implement it.
