### ISSUE TITLE
Missing API to create bitvector from value

### ISSUE THREAD

**Issue by mkeeter** [prove-rs/z3.rs#8]
I'm trying to do math with bitvectors, and running into what seems like a missing API: I don't see any way to create a bitvector from an integer or bool array.

For example:
```
    let cfg = Config::new();
    let ctx = Context::new(&cfg);
    let b = ctx.named_bitvector_const("bv", 4);
    let s = Solver::new(&ctx);
    s.assert(&b._eq(&ctx.from_u64(1)));
```
will print the error message 
```
Error: Sorts (_ BitVec 4) and Int are incompatible
```

My suggested fix is to add `pub fn from_u64(ctx: &'ctx Context, u: u64 -> Ast<'ctx>` to the `Sort` type, with an implementation that calls `Z3_mk_unsigned_int64()` using the given sort.  This works for integer, bit-vector, and finite-domain sorts.

Is this something that you'd accept a PR for (or want to implement yourself)?

**Comment by waywardmonkeys** [comment]
Sorry for the delay in responding. Daughter is sick, so am afk a lot.

A PR would be great!

**Comment by mkeeter** [comment]
No worries!  When you have time, I've opened a PR at #9.

**Comment by mkeeter** [comment]
Merged!
