### ISSUE TITLE
Static-link-z3 build should be parallelized

### ISSUE THREAD

**Issue by lzybkr** [prove-rs/z3.rs#82]
The static link build is pretty slow.

On Windows, the simplest thing is to add
```rust
        cfg.cxxflag("-MP");
```

This is a huge win on my 32 core build machine - going from I don't even know how long (30 minutes?) to around 7 minutes.

An incremental improvement is to also build in parallel with msbuild:

```rust
    cfg.build_arg("-m");
```

This shaved another 2 minutes off the build, maybe it could be improved even better as I'm sure there was some contention over cores, but maybe it's good enough.

I tried setting NUM_JOBS to get `cmake` to add `-m` automatically but for whatever reason it didn't seem to work for me.

Would a Windows only PR be welcome?

**Comment by fitzgen** [comment]
Sure thing! Thanks.
