### ISSUE TITLE
Support for recursive datatype

### ISSUE THREAD

**Issue by taegyunkim** [prove-rs/z3.rs#90]
Similar to what's implemented in python binding. https://z3prover.github.io/api/html/namespacez3py.html#a2aae8887c59dd8d4c298e6c0c05405d1

**Comment by fitzgen** [comment]
We have bindings to `Z3_mk_datatypes` in `z3-sys`, so we just need to add the high-level API. Are you interested in contributing this?

**Comment by taegyunkim** [comment]
@fitzgen Yes, unless someone started working on this.

**Comment by fitzgen** [comment]
I don't think anyone has, so please go for it! :)

**Comment by fitzgen** [comment]
Fixed in #93
