### ISSUE TITLE
Dynamic linking doesn't work on windows

### ISSUE THREAD

**Issue by Trolldemorted** [prove-rs/z3.rs#96]
Your code expects a z3.lib and z3.dll:

https://github.com/prove-rs/z3.rs/blob/3c6ab61482c64b083e79e6ccf550a5fb1e87b0a9/z3-sys/src/lib.rs#L1562-L1563

But building z3 outputs a libz3.lib and libz3.dll.

I checked how debian [packs libz3](https://packages.debian.org/de/sid/libz3-dev), and they ship a libz3.so, not a z3.so. Why do you try to link against z3 instead of libz3, and on what platforms does that work?

**Comment by fitzgen** [comment]
Thanks for reporting this issue.

On unix-based OSes, the "lib" prefix is already added, e.g. you specify the `-lpthread` CLI flag to a C compiler to explicitly link to `libpthread.so`.

We've had some issues in the past with z3 adding the lib prefix even on windows, but I'm not sure if that is what is going on here. In general, I'm far from a windows and cmake guru, so if you figure out what is going on here and can make a PR that would be very appreciated!

**Comment by Trolldemorted** [comment]
Could you release a version that includes this fix?

**Comment by fitzgen** [comment]
Published!
